### PR TITLE
:bug: Fix get_ and set_ prefix loop in __getattr__

### PR DESCRIPTION
**Pull request by shahyar**

### CODE REVIEW

**Comment by shahyar** [comment]
Apologies for the pull request spam for this method. I haven't written python in a long time. This should avoid further problems with the magic of get_prop and set_prop attempting to prepend get_ and set_, respectively.

**Comment by leolabs** [comment]
Haha, all good :)

I'll test the whole thing thoroughly this evening before merging and will publish a new version of AbletonJS then.

**Comment by leolabs** [comment]
Hey @shahyar,

Sorry that it took a bit longer than expected. I ran across a few more problems with the new changes so I chose another approach to this (see [Interface.py](https://github.com/leolabs/ableton-js/blob/5c39465e594dde900f16a61997f929879dfa60f2/midi-script/Interface.py#L28-L41)).

This should solve all issues. In the future, I'm planning to add support for more commands out of the box, without the need to call `sendCommand` manually, but your PR has helped greatly in cleaning up the Python side of this project 👍

**Comment by leolabs** [comment]
I forgot to mention, the new release is a pre-release for now as I want to be 100% sure the changes don't introduce any problems. You can install it by running `npm i ableton-js@next` or `yarn add ableton-js@next`.

**Pull request merged**
