### PR TITLE
Browsing and loading functionalities

### PR DESCRIPTION
**Pull request by coeur-de-loup**

### CODE REVIEW

**Comment by coeur-de-loup** [comment]
I think it would be best to optimize caching on Browser functions instead of always asking the api? Not sure how to do this properly...

**Comment by leolabs** [comment]
Hey @coeur-de-loup, thank you for the PR, and please excuse my late reply! I'll check it out soon!

**Comment by leolabs** [comment]
I'll make some adjustments to the code after merging, but this looks great!

**Comment by coeur-de-loup** [comment]
First ever contribution! Thanks for approving, I'll continue building on it!

**Pull request merged**
